### ISSUE TITLE
Jenkins warning "You have data stored in an older format and/or unreadable data."

### ISSUE THREAD

**Issue by leonpros** [qaprosoft/qps-infra#100]
Jenkins ver. 2.191

**Unreadable Data**
It is ok to leave unreadable data in these items/records, as Jenkins will simply ignore it. To avoid the log messages at Jenkins startup you can permanently delete the unreadable data by resaving these items/records using the button below the list.

Type | Name | Error
-- | -- | --
org.jenkinsci.plugins.workflow.job.WorkflowJob | .../API-Tests | MissingFieldException: No field 'usePrefinedVariables' found in class 'org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript'
com.cloudbees.hudson.plugins.folder.Folder | Management_Jobs | CannotResolveClassException: io.jenkins.blueocean.service.embedded.BlueOceanUrlAction
org.jenkinsci.plugins.workflow.job.WorkflowJob | .../Mobile-Android | MissingFieldException: No field 'usePrefinedVariables' found in class 'org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript'
hudson.plugins.sonar.SonarGlobalConfiguration | SonarGlobalConfiguration | CannotResolveClassException: hudson.plugins.sonar.SonarGlobalConfiguration$$Lambda$100/1630958061
org.jenkinsci.plugins.workflow.job.WorkflowJob | launcher | MissingFieldException: No field 'usePrefinedVariables' found in class 'org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript'
org.jenkinsci.plugins.workflow.job.WorkflowJob | .../Mobile-iOS | MissingFieldException: No field 'usePrefinedVariables' found in class 'org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript'
org.jenkinsci.plugins.workflow.job.WorkflowJob | .../Sanity-Tests | MissingFieldException: No field 'usePrefinedVariables' found in class 'org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript'
org.jenkinsci.plugins.workflow.job.WorkflowJob | .../Web-Test | MissingFieldException: No field 'usePrefinedVariables' found in class 'org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript'

**Comment by vdelendik** [comment]
@leonpros most of the warnings seems are fixed in 4.9 [jenkins-master](https://github.com/qaprosoft/jenkins-master/releases/tag/4.9) release where we upgraded Jenkins to 2.214 and synced all out-dated plugins,
