### ISSUE TITLE
Put ghprb-token setup steps into documentation

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-infra#103]
4.9 jenkins-master setup ghprhook-token by default
Put setup steps into documentation how to configure ghprb-token

**Comment by vdelendik** [comment]
@okamara, please add steps howto configure/verify github pull request checker plugin in configuration guide

**Comment by okamara** [comment]
The following steps are added: 
### Easy to Use Jenkins
 Preconditions:

1. Jenkins is installed and started
2. Generate "Git personal access token" 
### How to Generate "Git personal access token"
1. Sign in to github
2. In Left menu select "Settings" from the list
3. Select "Developer settings"
4. Select "Personal access token"
5. Click "Generate token"
6. Remember it or save

### 1:Update Jenkins credentials
 
Steps:
1.Open Jenkins

2.Click on Credentials in the left menu

3.Select "ghprbhook-token" and click on the link

4.Click on Update in the left menu

5.Enter Username e.g."username"

6.Near Password click Change password

7.Enter value of "Git token access" that was generated before for this user

8.Save changes

**Comment by okamara** [comment]
Done in https://github.com/qaprosoft/qps-infra/pull/131

**Comment by okamara** [comment]
Done
