### ISSUE TITLE
No live video (VNC) for Tests via Zafira if 4445 port is not opened

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#108]
Run Full Regression job in Jenkins
Open Zafira test run
Open test
Verify that user can see actual video for test case 
Actual result: Black screen is instead of live video session

**Comment by vdelendik** [comment]
@okamara, please test using branch: "86".
sudo ./clear.sh required as globally approach was reorganized. Moreover I recommend to remove completely qps-infra and clone again.
As a fix we moved selenoid into the same docker network and setup iintegration via container names, i.e. no more 4445 needed.
PR: https://github.com/qaprosoft/qps-infra/pull/113

**Comment by okamara** [comment]
Verified on #86. Fixed.
