### ISSUE TITLE
JENKINS_JOB_URL_VISIBILITY should be True

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#112]

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/111

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/73838469-cc30e380-4824-11ea-97ae-edd2cf96edec.png)

**Comment by ilya-varchenya** [comment]
Fixed to 4.9
Reassign to 4.10

**Comment by vdelendik** [comment]
@ilya-varchenya you didn't push changes to master yet so label ready-for-qa is invalid
@okamara ^^^

**Comment by okamara** [comment]
Verified on master branch. Fixed.
