### ISSUE TITLE
inject "docker-compose rm -fv" into the stop operation

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#114]
let's inject byde fefault below step into the stop.sh script:
docker-compose rm -fv

but sometime I need ability to stop everything and keep containers. So let's add optional argument like "--no-rm false" into the bash script.

i.e. to stop only I have to run
./stop.sh --no-remove
or
./stop.hs --keep-containers
let's discuss logic in advance

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/115
