### ISSUE TITLE
Add volume sharing for ftp container

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/qps-infra#117]
By default we use approach to get video artifacts for zafira from ./selenoid/video folder. We need share /share/ftp folder to ./selenoid/video as well. Update docker-compose.yml for ftp container:
`volumes: - $PWD/selenoid/video:/share/ftp`
Also, we need default permissions for ./selenoid/video folder -> 777.

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/119

**Comment by dhreben** [comment]
Fixed.
<img width="456" alt="Screen Shot 2020-04-06 at 12 39 33" src="https://user-images.githubusercontent.com/50950954/78545097-df9c0300-7803-11ea-8a53-f676869f835a.png">
