### ISSUE TITLE
Update links for content links in Readme

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#123]
Now all details are in https://github.com/qaprosoft/qps-infra/blob/master/docs/getting_started.md
Need to update content links according to correct link on prod for:
Software prerequisites
Initial setup
Services start/stop/restart
Env details
Documentation and free support

**Comment by vdelendik** [comment]
let's assume current structure is ok: https://qaprosoft.github.io/qps-infra/
![image](https://user-images.githubusercontent.com/4551455/81875801-ca945b80-9589-11ea-9201-6d8b3ae5376e.png)

**Comment by okamara** [comment]
Done.
