### ISSUE TITLE
5.0: Video exception is not published to FTP

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-infra#125]
Steps:

1.Run Mobile-Android-Demo-Test
2.Tap Console Output

Actual result: Video exception is not published to FTP

**Comment by vdelendik** [comment]
identified issue on pureftpd container side. Fixed on stage:
https://github.com/qaprosoft/pure-ftpd/issues/1

@dhreben ping me to define test strategy for that ticket

**Comment by dhreben** [comment]
Fixed.
