### ISSUE TITLE
Logs don't work, no redirection to the Zafira

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-infra#127]
Precondition:
Open http://stage.solvd.com/jenkins/
Steps:
1. Run Mobile-Android-Demo-Test
2. Tap Console Output
3. Tap ZafiraReport
4. Tap Logs in the Failed test

Actual result: Logs don't work, no redirection to the Zafira

**Comment by vdelendik** [comment]
configuration mismatch due to the testing new sub-domains approach:
Refused to display 'http://zafira-stage.solvd.com/app/tests/runs/154/info/774' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by vdelendik** [comment]
@dhreben 
issue can be tested on demo.qaprosoft.com server

**Comment by dhreben** [comment]
Fixed
