### ISSUE TITLE
Add description for zafiraServiceURL and zafiraAccessToken fields on create organization page

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#128]
Steps:
1. Open Create organization page 
2. Verify that zafiraServiceURL and zafiraAccessToken fields  have description how to enter value to the field
<img width="1094" alt="Screen Shot 2020-03-31 at 1 51 39 PM" src="https://user-images.githubusercontent.com/32964663/78062358-426e4400-7397-11ea-9c2d-635ee6ea1bc1.png">

**Comment by vdelendik** [comment]
@okamara it can be found in 4.10.1 jenkins-master.
it is recommended to do "sudo ./clear.sh"

**Comment by okamara** [comment]
Verified.
<img width="538" alt="Screen Shot 2020-04-08 at 1 58 02 PM" src="https://user-images.githubusercontent.com/32964663/78776720-004d8f80-79a1-11ea-88f9-5eddfe485fb1.png">
