### ISSUE TITLE
switch to lightweight jenkins-slave:latest-alpine in default setup 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#129]
For api and web jobs it is enough to use latest-alpine images:
qaprosoft/jenkins-slave:latest-alpine

ubuntu "latest" is twice bigger and has android sdk components installed for android mcloud slave

**Comment by vdelendik** [comment]
fix: https://github.com/qaprosoft/qps-infra/commit/dcec6b50c23c3de028464ac6fec3e93e1f96a2c1

@okamara test scenario:
inside qps-infra
1) sudo ./clear.sh
2) git pull
3) ./start.sh
... register organization, repo and run web/api jobs
-> "docker images" command should display "qaprosoft/jenkins-slave:latest-alpine" image on the system
-> api/web tests could run as usual

**Comment by okamara** [comment]
@vdelendik I see qaprosoft/jenkins-slave:latest ->
<img width="895" alt="Screen Shot 2020-04-08 at 4 48 58 PM" src="https://user-images.githubusercontent.com/32964663/78791693-df913400-79b8-11ea-9226-633b8d61c6bb.png">
is it correct?

**Comment by okamara** [comment]
Verified .
![Uploading Screen Shot 2020-04-08 at 5.31.27 PM.png…]()
