### ISSUE TITLE
update zafira and ui to 4.1.90 and 1.38 versions

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#130]
subj

**Comment by vdelendik** [comment]
updated versions and applied changes to sql init scripts: https://github.com/qaprosoft/qps-infra/commit/11be1c598b3270a86a521ec73230f627bea71a86

test scenario:
1) sudo ./clear.sh
2) make sure you are on master branch of qps-infra
3) get latest changes:
```git pull
```
4) ./start.sh
5) do regular acceptance testing

**Comment by okamara** [comment]
Verified. Done.
