### ISSUE TITLE
investigate possibility to declare optional upstream servers in nginx

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#132]
to be able to add/disable components we should the issue with nginx which can't start if any of the server is not available.
there is recommended workaround which use variable in proxy_pass declaration.

**Comment by vdelendik** [comment]
in qps-infra:5.0-beta8 branch most of the references are applied using variables instead of upstreams declaration, for example: https://github.com/qaprosoft/qps-infra/commit/cd2a9dde92d137a4514237a33755126e342526f4

to test this feature we should:
1) clear, scan and run nightly_regression jobs
2) stop one of the server, for example selenoid:
docker rm -f selenoid
-> jenkins, zafira and default site works as expected. Web test fail due to the absence of the selenoid
3) restart nginx
docker restart nginx
-> in old version nginx couldn't be started. Using current approach it should be restarted without any problem
4) run again web test with non started selenoid
-> again web test fail
5) start selenoid
./start.sh
6) run web test
-> everything should be fine now without additional nginx restart

**Comment by okamara** [comment]
Created a separate issue for Rerun job issue. https://github.com/qaprosoft/jenkins-master/issues/217
