### ISSUE TITLE
rename QPS_HOST to INFRA_HOST

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#137]
INFRA_HOST is the global var which should be registered in shared .env
All sub-components which use it should be refactored.
jenkins-master: https://github.com/qaprosoft/jenkins-master/issues/201
TODO: inspect all qps repositories and update accordingly

**Comment by vdelendik** [comment]
no QPS_HOST declaration in qps-infra anymore.
INFRA_HOST is used starting from 5.0-beta8.
The same changes applied for qps-pipeline: develop and jenkins-master: 5.0-beta8

**Comment by dhreben** [comment]
Verified
