### ISSUE TITLE
during start.sh verify if network exists

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#138]
don't create "infra" network during start if it already exists.
update shell script to verify preliminary to avoid this errot message:
Error response from daemon: network with name infra already exists

**Comment by sandinosanchez** [comment]
@okamara 
changes could be seeing here #141 

Pre-conditions:
1. https://github.com/qaprosoft/qps-infra/ cloned
2. git checkout 5.0-beta4
3. setup.sh and start.sh executed at least one time

Steps:
1. run docker network ls | grep infra
2. run start.sh

Expected result:
1. network id,  infra, bridge, local
2. start.sh started no error message in the beginning showing "Error response from daemon: network with name infra already exists"

**Comment by okamara** [comment]
Tested on qaprosoft/jenkins-master:5.0-beta9 and qps-infra: 5.0-beta8. fixed.
