### ISSUE TITLE
restore default integration in infra

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#140]
jenkins, rabbitmq and test environment providers should be enabled again.
it should be organized via additional sql we do during reporting pg repo init.
in the 5.0-beta3 we removed all integrated queries from the default sql queries

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-infra/commit/3b50c8729e83347e9875595476dc2791e6187a5e

by default we enabled again integrations for:
-jenkins
-rabbitmq
-selenium (test execution provider)

test scenario:
./clear.sh
git pull (develop branch!)
./setup.sh <ip>
./start.sh

-> after logging to zafira above integrations are enabled and green

**Comment by okamara** [comment]
Tested on local env.
<img width="620" alt="Screen Shot 2020-05-14 at 12 20 00 PM" src="https://user-images.githubusercontent.com/32964663/81916995-479cf080-95dd-11ea-907a-a00a2c850a13.png">
<img width="549" alt="Screen Shot 2020-05-14 at 12 19 23 PM" src="https://user-images.githubusercontent.com/32964663/81917000-4966b400-95dd-11ea-890e-0545017dac97.png">
<img width="509" alt="Screen Shot 2020-05-14 at 12 18 25 PM" src="https://user-images.githubusercontent.com/32964663/81917009-4c61a480-95dd-11ea-9503-a0ad284e2fbc.png">
