### ISSUE TITLE
carina + zafira-client: lost [L000N] indexes

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#144]
in latest 6.4.35 carina and 4.2.70 zafira-client we don't see [L000N] postfixes for dataprovider tests.
CarinaReport:
![image](https://user-images.githubusercontent.com/4551455/80864911-8f8f4f80-8c8e-11ea-8cc7-c05e6ddf3733.png)

ZafiraReport:
![image](https://user-images.githubusercontent.com/4551455/80864929-a635a680-8c8e-11ea-8f97-7d4791719416.png)

**Comment by vdelendik** [comment]
fix might be tested running carina-demo from "#1006" branch.
we still continue to fix all regression after moving to the TestNG 7.1.0

**Comment by okamara** [comment]
Fixed.
