### ISSUE TITLE
most of the browser containers can't be stopped

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#145]
Error response from daemon: driver "aufs" failed to remove root filesystem for

ubuntu@ip-172-30-0-174:~/tools/qps-infra$ docker --version
Docker version 17.09.0-ce, build afdb6d4

**Comment by vdelendik** [comment]
issue is fixed by upgrading to latest docker version:
 docker --version
Docker version 19.03.8, build afacb8b7f0

**Comment by vdelendik** [comment]
verified on new demo env successfully

**Comment by okamara** [comment]
will be re-verified by Vadim.
