### ISSUE TITLE
find a way to use valid global var for sub-modules

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#146]
Jenkins sub-module should reuse valid global vars from .env file
For example:
https://github.com/qaprosoft/qps-infra/blob/c41c3705845b8cd59e492b8e3b8ad3fd50f7a59c/jenkins/variables.env#L5

**Comment by vdelendik** [comment]
all variables in this file are from .env: https://github.com/qaprosoft/qps-infra/blob/3b50c8729e83347e9875595476dc2791e6187a5e/jenkins/docker-compose.yml#L11
test scenario - setup on non "demo.qaprosoft.com" server. Everything should work as usual

**Comment by okamara** [comment]
all variable from docker-compose.yml are now in .env .
