### ISSUE TITLE
setup.sh should be prohibited for "localhost" or "127.0.0.1" hostname

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#147]
improve setup.sh script to avoid any configuration if localhost or 127.0.0.1 is provided.
publicly available to client ip address or dns name should be provided

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/158

**Comment by vdelendik** [comment]
available for testing in qps-infra develop branch.
try to run
./setup.sh localhost
./setup.sh 127.0.0.1

-> error message should be displayed that fully qualified domain name or ip address should be used

**Comment by okamara** [comment]
<img width="993" alt="Screen Shot 2020-05-07 at 12 41 27 PM" src="https://user-images.githubusercontent.com/32964663/81279684-23329880-9060-11ea-89b4-a49ea59ce931.png">
try to run
./setup.sh localhost - Test passed
./setup.sh 127.0.0.1 - Test faild, as I haven't got error message.

**Comment by okamara** [comment]
Fixed.
