### ISSUE TITLE
WARNING: The POSTGRES_PASSWORD variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#150]
POSTGRES_PASSWORD is not available - need check and fix

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/qps-infra/commit/0c19f08970c4ee3983c569b24c0297ca8262e365

valid name is POSTGRES_PASSWORD for the var which is declared in .env.original and used by reporting-service/docker-compose.yml

**Comment by vdelendik** [comment]
test scenario: during start/stop.sh no warning should appear in logs.

**Comment by okamara** [comment]
Verified on qaprosoft/jenkins-master:5.0-beta9 and qps-infra: 5.0-beta8. Fixed.
