### ISSUE TITLE
Zafira logo in Safari and Firefox is displayed incorrect on pin tab menu

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-infra#151]
1 case:

1. Open Safari 
2.Enter http://demo.qaprosoft.com
3. On tab menu tap right click mouse Zebrunner starter
4. Tap "Pin Tab"
    Actual result: The Jenkins logo is displayed 

2 case:

1. Open Safari 
2.Enter http://demo.qaprosoft.com
3. Tap Zafira
4. Enter username and password
5. Tap "Pin Tab"
    Actual result: The Jenkins logo is displayed 

3 case.

1.Open Firefox
2.Enter http://demo.qaprosoft.com
3. On tab menu tap right click mouse Zebrunner starter
4. Tap "Pin Tab"
    Actual result:  Incorrect logo is displayed.

<img width="672" alt="Screen Shot 2020-05-04 at 14 10 04" src="https://user-images.githubusercontent.com/50950954/80960188-0d7b6400-8e11-11ea-9760-1d22cc06c97d.png">

**Comment by vdelendik** [comment]
it should be fixed in scope of https://github.com/qaprosoft/qps-infra/issues/227 ticket

**Comment by dhreben** [comment]
Fixed:
Firefox:
<img width="690" alt="Screen Shot 2020-07-27 at 14 28 40" src="https://user-images.githubusercontent.com/50950954/88537235-dda9ba00-d015-11ea-80fa-4ea50d15c0f8.png">
Safari:
<img width="615" alt="Screen Shot 2020-07-27 at 14 33 01" src="https://user-images.githubusercontent.com/50950954/88537376-2497af80-d016-11ea-8d71-11115f017800.png">
