### ISSUE TITLE
Zafira test launcher is not active 

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#154]
Tested on qps-infra: 5.0-beta8, qaprosoft/jenkins-master:5.0-beta9
Steps:
-Set GITHUB_CLIENT_ID= and  GITHUB_CLIENT_SECRET=
-Set Jenkins, ZEBRUNNER in app
Actual result: Launcher is not active

<img width="875" alt="Screen Shot 2020-05-05 at 11 55 55 AM" src="https://user-images.githubusercontent.com/32964663/81049880-bf756780-8ec7-11ea-836e-2fee78be4dfb.png">

**Comment by vdelendik** [comment]
@okamara, fix is delivered:
1) changes should be applied in .env.originial before setup.sh
-> please test that it works as expected

2) also submit a doc issue to document this requirement as of now on the documentation side

**Comment by okamara** [comment]
Fixed. Ticket created https://github.com/qaprosoft/qps-infra/issues/159
