### ISSUE TITLE
Impossible set own AUTH_TOKEN_SECRET and CRYPTO_SALT

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#155]

**Comment by okamara** [comment]
Tested on qps-infra: 5.0-beta8, qaprosoft/jenkins-master:5.0-beta9

**Comment by vdelendik** [comment]
fix delivered to develop branch of qps-infra: https://github.com/qaprosoft/qps-infra/commit/7d27446b358672848c74601209bf8bb1ab5a614a

changes should be applied in .env.original before setup.sh!

appropriate doc ticket should be submitted

**Comment by okamara** [comment]
Fixed.
