### ISSUE TITLE
Integration with CI is not working on zafira

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#160]
<img width="990" alt="Screen Shot 2020-05-07 at 2 43 52 PM" src="https://user-images.githubusercontent.com/32964663/81291123-ebcce780-9071-11ea-8adb-4be285cab553.png">
<img width="441" alt="Screen Shot 2020-05-07 at 2 46 53 PM" src="https://user-images.githubusercontent.com/32964663/81291137-eff90500-9071-11ea-8919-8c7fbe9337be.png">
Integration with CI is not working on zafira
Impossible to Rerun-test from Jenkins

**Comment by vdelendik** [comment]
it should be fixed in scope of the integrations fixes

**Comment by okamara** [comment]
Tested on local env. Fixed.
