### ISSUE TITLE
ROOT_URL is wrong

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#161]
Steps:
1. Start Web-demo test in Jenkins on local env
2. Open zafira and Open Web-demo test via link 
Actual result: Link is incorrect(demo env link) and HTTP ERROR 404 Not Found is on the page

Env: qaprosoft/jenkins-master:5.0-beta9 and qps-infra: 5.0-beta8

**Comment by vdelendik** [comment]
changes are here: https://github.com/qaprosoft/qps-infra/commit/d7551120793fbf5d7a2a1b8ebfb2c00619b38dfc

do clear.sh and pull from develop (qps-infra)

**Comment by okamara** [comment]
Verified.
