### ISSUE TITLE
Using https should be configurable in .env.original

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#162]

**Comment by vdelendik** [comment]
done: #239

testing scenario:

clone recursively qps-infra using develop branch
git clone --recurse-submodule --branch develop https://github.com/qaprosoft/qps-infra.git

configure it using setup interactive installer/configurator:
./zebrunner.sh setup
-> provide **https** protocol, hostname and port
Note: final infra url should be like https://54.110.24.15:443

inspect all kind of variables.env and nginx default conf. it should be https and 443 where applicable
Important! By default env might not be started successfully. This ticket only organized vars/configuration registration and not SSL setup!

**Comment by okamara** [comment]
Tested on develop. https is not working for me.
