### ISSUE TITLE
root_url still present in variables.env for jenkind docker-composer

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#163]
https://github.com/qaprosoft/qps-infra/blob/d7551120793fbf5d7a2a1b8ebfb2c00619b38dfc/jenkins/variables.env#L2

**Comment by vdelendik** [comment]
during the test please verify:
1) such new variables declared in .env.original
+JENKINS_ADMIN_USER=admin
+JENKINS_ADMIN_PASS=changeit
+JENKINS_ROOT_EMAIL=qps-auto@qaprosoft.com
+# comma separate administrator emails to receive all kind of system notifications (mostly about pipeline/jobdsl failures)
+JENKINS_ADMIN_EMAILS=qps-auto@qaprosoft.com

2) no "jenkins/variables.env" file anymore
3) regular basic acceptance with running all kind of jobs

**Comment by okamara** [comment]
I see that no "jenkins/variables.env" file anymore.
But I can't see .env.original. 
@vdelendik where I should see .env.original now?

**Comment by vdelendik** [comment]
.env.original as usual in the main qps-infra folder

**Comment by okamara** [comment]
Reverified. Fixed.
@dhreben could you please re-run smoke.

**Comment by dhreben** [comment]
@vdelendik  Carina-demo doesn't display all Runs, onPush-carina-demo failed
Open new ticket
https://github.com/qaprosoft/qps-infra/issues/166
