### ISSUE TITLE
Add sonarqube token creation into docs

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-infra#164]
Starting from infra(zebruner starter) 5.0 in order to fully integrate sonarqube we need to create a sonar token via sonar ui, and a credential in jenkins.

Steps :

1. Open your.domain.com/sonarqube
2. Login with admin/admin credentials
3. [OPTIONAL] change password if u need it
4. Browse user tokens (click login icon -> My account -> security)
5. Generate user token
6. Open jenkins and generate new credential (secrect text) id = sonar-token, desc = sonar-admin, secret = your sonar token from step 5
7.  In jenkins global config assign the new token to the sonarqube server config and save config

**Comment by okamara** [comment]
@sandinosanchez could you please add link for docs where it is possible to test?

**Comment by sandinosanchez** [comment]
@okamara This is information that should be added into the documentation for the infra, i will add that documentation and update here soon.

**Comment by sandinosanchez** [comment]
@okamara changes could be seeing in #169

**Comment by dhreben** [comment]
Verified.
1. All information added into the  documentation.
<img width="777" alt="Screen Shot 2020-05-14 at 16 47 57" src="https://user-images.githubusercontent.com/50950954/81942345-b04a9400-9602-11ea-95f6-d072376dd7d2.png">

2. SonarTest token and credential in Jenkins were generated and assigned to the SonarQube server config.

![Screen Shot 2020-05-14 at 16 46 56](https://user-images.githubusercontent.com/50950954/81945105-52b84680-9606-11ea-8018-8e8ee4995185.png)
