### ISSUE TITLE
Carina-demo doesn't display all Runs, onPush-carina-demo failed 

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-infra#166]
Precondition:
Open http://54.193.74.120/jenkins/

Steps:
1.Tap okamara
2.Tap RegisterRepository
3.Tap Build with Parameters
4.Run Build
5.Tap carina-demo
     Actual result: Carina-demo doesn't display all Runs, onPush-carina-demo failed 

Please see screenshots:
<img width="1069" alt="Screen Shot 2020-05-10 at 13 35 11" src="https://user-images.githubusercontent.com/50950954/81497945-90496680-92ca-11ea-9bc6-6f0cd10b40b3.png">
<img width="910" alt="Screen Shot 2020-05-10 at 14 08 56" src="https://user-images.githubusercontent.com/50950954/81497946-93dced80-92ca-11ea-93fb-eeadb45cb6e3.png">

**Comment by sandinosanchez** [comment]
@dhreben  Try same test in sonar-scanner branch or wait for merge of [#731](https://github.com/qaprosoft/qps-pipeline/pull/731)

**Comment by vdelendik** [comment]
@dhreben, @okamara hotfix delivered to develop branch of qps-pipeline.
@sandinosanchez, using "maven" node for cloning and scanning was a mistake: https://github.com/qaprosoft/qps-pipeline/commit/ef095b5b8602b0bdabdb1555e80c6088526b682f

So it seems like we can use another clone only for sonar on maven slave... Need to think howto init ISCM instance for this class as well.

**Comment by okamara** [comment]
Fixed.
