### ISSUE TITLE
Add sonarqube configuration into docs

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-infra#167]
Starting from infra(Zebrunner starter) 5.0 in order to fully integrate sonarqube with the infra it is mandatory to create a token and add it to jenkins as a credential(see #164 for more info). Moreover it is also mandatory if you want to enable static code analysis to have a ".sonarqube" file in your project root directory.
- For enabling static code analysis create a .sonarqube file in your project root directory and add the following properties(example from carina-demo):
   ```
   sonar.projectBaseDir=.
   sonar.projectName=carina-demo
   sonar.projectKey=carina-demo
   sonar.java.source=1.8
   sonar.sources=src/main
   sonar.tests=src/test
   sonar.java.binaries=target/classes
   sonar.junit.reportPaths=target/surefire-reports
   ```
- For multi-module maven projects add the following prop to the above file(example from carina):
   ```
   sonar.modules=carina-api,carina-aws-s3,carina-commons,carina-core,carina-crypto,carina-
   dataprovider,carina-appcenter,carina-proxy,carina-reporting,carina-utils,carina-webdriver
   ```
Once such file is created after each push or pr on your repository the sonar scanner will be executed.
In order to enable pull request decoration(auto comments with sonar issues in the pr) follow the next steps:
1. Navigate to your jenkins instance configuration page
2. In the global variables section add new variable, name = GITHUB_OAUTH_TOKEN value= your github token(with write permissions). This token will be used for automatic comments into pr.

**Comment by sandinosanchez** [comment]
@okamara Changes could be seeing in #169

**Comment by dhreben** [comment]
Verified
<img width="970" alt="Screen Shot 2020-05-14 at 16 13 22" src="https://user-images.githubusercontent.com/50950954/81938632-d883c400-95fd-11ea-9ab4-b3bda78c9d74.png">
