### ISSUE TITLE
default Z icon doesn't display for the active tab

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/qps-infra#170]
Steps:
1. Open site e.g. google.com
2. Open http://demo.qaprosoft.com 
2. Switch into an active tab on the browser Zebrunner Starter

      Actual result: default Z icon doesn't display for the active tab

Please see screenshot:
<img width="450" alt="Screen Shot 2020-05-14 at 19 27 00" src="https://user-images.githubusercontent.com/50950954/81959944-e561e100-9618-11ea-9f86-b767d4716a2c.png">

A possible solution of this issue:

Case 1  With HTML :

1.Add in HTML
<img width="536" alt="Screen Shot 2020-05-14 at 20 00 09" src="https://user-images.githubusercontent.com/50950954/81963257-881c5e80-961d-11ea-88c3-ed91f0d6ac8a.png">
2.Check that the ico file type is included in the listing in the web server configuration file:

<img width="416" alt="Screen Shot 2020-05-14 at 20 02 02" src="https://user-images.githubusercontent.com/50950954/81963491-d598cb80-961d-11ea-9cbe-d4669ad24852.png">
Case 2: Without HTML:
<img width="466" alt="Screen Shot 2020-05-14 at 20 03 12" src="https://user-images.githubusercontent.com/50950954/81963602-fa8d3e80-961d-11ea-903f-f6090af5f7e0.png">

**Comment by vdelendik** [comment]
it is planned to remove this page at all so fixes not needed in the current states
