### ISSUE TITLE
Modify sonarqube docs to handle new sonar token behaviour 

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/qps-infra#174]
in [qps-pipeline#745](https://github.com/qaprosoft/qps-pipeline/pull/747) there was a set of modifications to the sonarqube token configuration, need to update sonar docs to display such changes.

1. Token assignation is now part of registerOrganization job.
2. Modify .sonarqube file properties to match https://github.com/qaprosoft/carina-demo/commit/ea5ee9576770215dc2e9b308fbad556c2b33f73f for single maven projects.
3. Modify .sonarqube file properties to mach https://github.com/qaprosoft/carina/commit/3897b8c32990e82e212bfc749a0571f9599b6760 for multi maven projects.
4. Add set of permissions that the sonar token should have.

**Comment by sandinosanchez** [comment]
changes could be seeing in #178

**Comment by dhreben** [comment]
Verified
<img width="554" alt="Screen Shot 2020-05-20 at 13 40 59" src="https://user-images.githubusercontent.com/50950954/82437529-3c940580-9aa0-11ea-9c4b-a0363ab00b61.png">
