### ISSUE TITLE
by default is not enabled integrations for rabbitmq

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#177]
by default is not enabled integrations for rabbitmq:
Fields are not populated by default
<img width="696" alt="Screen Shot 2020-05-19 at 7 48 05 PM" src="https://user-images.githubusercontent.com/32964663/82362290-cac2aa00-9a14-11ea-9d18-a871e5542167.png">

**Comment by vdelendik** [comment]
available in master. need to clear and retest

**Comment by okamara** [comment]
Tested. Fixed.
