### ISSUE TITLE
invalid documentation mkdocs format detected for sonarqube

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#188]
https://qaprosoft.github.io/qps-infra/config-guide/

Editing docs in github should be done carefully. Not all alignments supported by mkdocs.
As result formatting is corrupted: 
![image](https://user-images.githubusercontent.com/4551455/83035527-3ffc3380-a042-11ea-9824-eb7473eb0baa.png)

@sandinosanchez please adjust using compatible controls

**Comment by okamara** [comment]
Fixed.

**Comment by okamara** [comment]
need add some updates
