### ISSUE TITLE
add configuration manager support on Mac for browsers images upgrade

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#189]
Subj

**Comment by ilya-varchenya** [comment]
Could you provide more details what configuration manager support
I found similar case https://github.com/qaprosoft/qps-infra/blob/3ab7598e7b51664a6125675fcfd87cd613432738/selenoid/update.sh#L3
and created updater script for mac on it's base

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/193

**Comment by vdelendik** [comment]
according to the https://aerokube.com/cm/latest/#_quick_start_guide cm_linux_amd64 binary is valid for mac as well.
@ilya-varchenya, so try to do setup on your local mac to see if it works. Hopefully no changes requires at all to solve this ticket

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/84023874-8c743700-a991-11ea-8ff3-53b1293b2fd3.png)
No, we can't use the same binary file

**Comment by ilya-varchenya** [comment]
Test scenario:
Try to run `qps-infra/selenoid/update.sh` script from any directory on **Mac**
Also check it on Linux machine
1) cm binary file must be downloaded into qps-infra/selenoid/bin directory
2) several docker images should be dowloaded 
![image](https://user-images.githubusercontent.com/44428408/84264373-be200600-ab29-11ea-8d84-0d9199f3d3dc.png)
Note: two latest images firefox, opera, chrome should be downloaded

**Comment by okamara** [comment]
Tested on jenkins-master:5.1-beta1, qps-infra - develop. Fixed.
