### ISSUE TITLE
doc: obsolete screenshots should be replaced

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#191]
please review using environment installed from master and replace obsolete screenshots in documentation.
https://qaprosoft.github.io/qps-infra/config-guide/#register-organization
![image](https://user-images.githubusercontent.com/4551455/83776238-9c89cf00-a690-11ea-82c1-c4e46df79c12.png)

**Comment by okamara** [comment]
https://github.com/qaprosoft/qps-infra/blob/master/docs/config-guide.md  - Config guide is updated

**Comment by okamara** [comment]
Images are updated according to 5.0.4 version.
