### ISSUE TITLE
get latest database sql from zebrunner master for 5.1

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#202]
We have to update our sql database scripts in infra as only below changes merged to zebrunner master!!! current PR to develop so we have to double check when changes appear in master branch!
https://github.com/zebrunner/zebrunner/pull/2150

**Comment by ilya-varchenya** [comment]
Updates from zebrunner 1.6

**Comment by okamara** [comment]
@ilya-varchenya could you please add details how to check this ticket

**Comment by ilya-varchenya** [comment]
@okamara, this ticket is related to zebrunner, so verify that our pipelines will work well and check zebrunner integration

**Comment by okamara** [comment]
zebrunner integration is not working correctly now. Scanning jenkins via zebranner can't be completed.

**Comment by okamara** [comment]
Created a new bug for launchers.
