### ISSUE TITLE
test new views and widgets without reference to created_at

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#203]
need setup infra from scratch using reporting-service sql queries from this branch: 
https://github.com/zebrunner/zebrunner/tree/ZEB-885/database/sql

the most risky areas - existing widgets and widget templates. So after setup we should 
1) run something (several crons)
2) wait 1 day to fill materialized total_view
3) review all existing boards/widgets - data should be displayed without error messages
4) create new widgets based on each widget template

As only testing is finished we can merge this PR:
https://github.com/zebrunner/zebrunner/pull/2151

**Comment by vdelendik** [comment]
synched with latest zafira sql queries including the changes for views and widgets:
https://github.com/qaprosoft/qps-infra/commit/e8041df7e42af80fed5e9c574e40ff04cc24dfdd.

test scenario is described above in ticket description

**Comment by okamara** [comment]
Verified. Fixed.
