### ISSUE TITLE
Combine update.sh and download.sh

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-infra#204]
We have two scripts update.sh and download.sh in qps-infra/selenoid/ for downloading new browser's images. Let's combine this scripts into one (update.sh)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/205

**Comment by ilya-varchenya** [comment]
Test scenario is the same as in https://github.com/qaprosoft/qps-infra/issues/189

**Comment by okamara** [comment]
Tested on jenkins-master:5.1-beta1, qps-infra - develop. Fixed.
