### ISSUE TITLE
Wrong link to test in Zafira report

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#206]
Tested: jenkins-master: 5.1-beta1,qps-infra- develop, pipeline- develop
Steps:
1. Run Web demo tests
2. Open Zafira report 
3. Click on link to test AUTO-0008
Actual result: 404 page is opened

<img width="1131" alt="Screen Shot 2020-06-11 at 6 48 32 PM" src="https://user-images.githubusercontent.com/32964663/84408031-4da1e380-ac14-11ea-84ea-977c8f02f0e5.png">

**Comment by vdelendik** [comment]
moved the ticket into the zebrunner project: https://github.com/zebrunner/zebrunner/issues/2179
