### ISSUE TITLE
Widget chart is shifted left

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#210]
Tested via qps-infra:develop; jenkins-master:5.1-beta3;pipeline-develop
Case1:
Steps:
1.Create a widget PASS RATE (PIE + LINE) 
2.Verify that widget looks correct on dashboard
Actual result: Widget chart is shifted left(see image)

<img width="489" alt="Screen Shot 2020-06-16 at 9 34 45 PM" src="https://user-images.githubusercontent.com/32964663/84815002-04d69a00-b01b-11ea-9baf-7cb6d9e30b51.png">

**Comment by vdelendik** [comment]
as designed for small size... there is improvement in zafira to add it with bigger size
