### ISSUE TITLE
After job scanning Console log contains errors

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#211]
Env. : jenkins:5.1_beta3;qps-infra - develop; pipeline- develop
I see that  job scanning contains error and some jobs run is failed e.g. "Build"
<img width="1108" alt="84667864-91099400-af2b-11ea-832e-5e4432c43d2c" src="https://user-images.githubusercontent.com/32964663/84893864-9e985880-b0a8-11ea-9a93-39c82e2693e3.png">
:

**Comment by ilya-varchenya** [comment]
Ticket isn't reproduced

**Comment by okamara** [comment]
This issue is not repro on release versions.
