### ISSUE TITLE
add "default" jenkins slave label for our single slave

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#218]
we have assign one more "default" label to our single slave.
change should be delivered in scope of 5.1 infra. appropriate ticket in qps-pipeline: https://github.com/qaprosoft/qps-pipeline/issues/834

**Comment by sandinosanchez** [comment]
feature delivered in #219 acceptance criteria of this ticket could be delivered with test steps provided in [#834](https://github.com/qaprosoft/qps-pipeline/issues/834)

**Comment by okamara** [comment]
Tested via #834
