### ISSUE TITLE
"API" is not visible in Environment column for Test runs in Zebruner

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#225]
Env.
jenkins-master:5.1, sonarqube:2.2 and stf:3.2, qps-infra:develop ,pipeline: 5.1
Steps:
1. Run Api tests via Jenkins
2. Open test runs in Zafira 
3. Verify that API test runs show "API" in Environment column
Expected:API test runs show "API" in Environment column
Actual:API test runs show "empty" in Environment column
<img width="1339" alt="Screen Shot 2020-07-14 at 2 45 15 PM" src="https://user-images.githubusercontent.com/32964663/87425933-28274180-c5e7-11ea-8c1e-5da69d0534a4.png">

**Comment by okamara** [comment]
Tested, Fixed.

**Comment by vdelendik** [comment]
fix is available in develop branch
