### ISSUE TITLE
integrate zebrunner insights 1.8 into the infra

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#227]

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-infra/pull/239

make sure to clone qps-infra develop recursively and setup using new approach:
git clone --recurse-submodule --branch "develop" https://github.com/qaprosoft/qps-infra.git
./zebrunner.sh setup

Important: as of now default **qpsdemo/qpsdemo** user will be created for Zafira. Use them to login and test jobs registration process

**Comment by vdelendik** [comment]
fixed: git clone --recurse-submodule --branch "develop" https://github.com/qaprosoft/qps-infra.git
./zebrunner.sh setup

**Comment by okamara** [comment]
Verified. Fixed.
