### ISSUE TITLE
integrate sonarqube as independent sub-module with appropriate setup block

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#235]
1) remove existing sonarqube folder from infra repo
2) register it as independent github submodule from https://github.com/zebrunner/sonarqube location
3) update setup.sh process to be able to enable/disable this component
4) For enabled case - register http://$INFRA_HOST/sonaruqbe
5) for disabled case - be able to provide any value for SONAR_URL var (required by CI/Jenkins layer)

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-infra/pull/238

during a testing we have to:
1) clone qps-infra for develop branch with recursive sub-modules pulling (to get latets sonarqube sources):
git clone --recurse-submodule --branch "develop" https://github.com/qaprosoft/qps-infra.git

2) setup env using new shell script:
./zebrunner.sh setup
Note: this is interactive shell script which can ask about enabling/disabling sonarqube module and INFRA_HOST

3) make sure for disabled sonarqube - appropriate service not started anymore

4) for enabled sonarqube we can start/stop/restart etc as part of the qps-infra

**Comment by okamara** [comment]
Tested on develop branch.
