### ISSUE TITLE
elastic search container doesn't work right after start

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#24]
After starting qps-infra elk container doesn't work as expected. As a hotfix we should:
1) run any test
2) restart elk

so need a way to determine valid solution to register exchange in rabbitmq right after startup. It should resolve elk issue

**Comment by hursevich** [comment]
Update username, password in definitions.json for RabbitMQ if you are not using default qpsdemo/qpsdemo user
