### ISSUE TITLE
Update script's logo

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-infra#241]
We have "ZEBRUNNER STARTER" in printed logo of configuration files.
Change it to "ZEBRUNNER CE"

**Comment by ilya-varchenya** [comment]
@ilya-varchenya Use [this site](http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=Zebrunner%20ce) as a tool

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/243

**Comment by ilya-varchenya** [comment]
Test scenario:
Check that "ZEBRUNNER CE" logo prints on console after running the script

**Comment by vdelendik** [comment]
PR merged so it might be tested using qps-infra and develop branch
https://github.com/qaprosoft/qps-infra/pull/243

**Comment by okamara** [comment]
Verified. Fixed.
