### ISSUE TITLE
integrate jenkins as independent sub-module

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#244]
https://github.com/zebrunner/jenkins-master
this repo should be added as sub-module into the qps-infra repo

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-infra/pull/239

testing scenario:
1) clone recursively qps-infra using develop branch
git clone --recurse-submodule --branch develop https://github.com/qaprosoft/qps-infra.git

2) configure it using setup interactive installer/configurator:
./zebrunner.sh setup
-> provide valid protocol, hostname and port
Note: final infra url should be like http://54.110.24.15:80

3) be able to login into the jenkins using admin/changeit
4) be able to register/scan repository and run **api** tests

**Comment by okamara** [comment]
Verified. Fixed.
