### ISSUE TITLE
made mcloud as independent repo and register it as sub-module

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#245]
subj

**Comment by vdelendik** [comment]
done. testing scenario:

clone recursively qps-infra using develop branch
git clone --recurse-submodule --branch develop https://github.com/qaprosoft/qps-infra.git

configure it using setup interactive installer/configurator:
./zebrunner.sh setup
-> provide valid protocol, hostname and port
Note: final infra url should be like http://54.110.24.15:80
Note2: make sure to enable mcloud component answering "y" for:
Enable Zebrunner Engine (Selenium Hub for Mobile - Android, iOS, AppleTV etc)?

be able to login into SmarttestFarm
http://hostname:80/stf

**Comment by dhreben** [comment]
Verified
<img width="722" alt="Screen Shot 2020-08-12 at 12 11 49" src="https://user-images.githubusercontent.com/50950954/89997795-5014ce00-dc95-11ea-80be-563b09227947.png">
