### ISSUE TITLE
add valid icon for default nginx index.html page

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#39]

**Comment by vdelendik** [comment]
Started huge refactoring of nginx static snd dynamic content

**Comment by vdelendik** [comment]
1) on default page "Welcome to ZEBRUNNER STARTER" message is displayed
2) when you open http://demo.qaprosoft.com and switch into another tab on browser - default Z icon should be displayed
![image](https://user-images.githubusercontent.com/4551455/80909601-2b25cc00-8d32-11ea-857b-f27d7e892bde.png)

**Comment by dhreben** [comment]
Safari, Firefox, Chrome doesn't display the logo.
Please see screenshot  Chrome
<img width="606" alt="Screen Shot 2020-05-04 at 13 38 09" src="https://user-images.githubusercontent.com/50950954/80958493-cc358500-8e0d-11ea-92d0-f067e86f093c.png">

**Comment by vdelendik** [comment]
@dhreben fixed logo only when you activate another tab:)
if it works, close it. for active tab submit a new ticket please with details howto enable this icon in browser:)

**Comment by dhreben** [comment]
@vdelendik  when active another tab, doesn't display the logo.
Chrome Ver. 81.0.4044.138
Firefox Ver.76.0.1
Please see screenshots:
 Chrome:
<img width="697" alt="Chrome" src="https://user-images.githubusercontent.com/50950954/81958518-cb270380-9616-11ea-9155-ed3bdf71e0e9.png">
Firefox:
<img width="716" alt="Firefox" src="https://user-images.githubusercontent.com/50950954/81958520-ccf0c700-9616-11ea-9b2f-ebb3a0f406ca.png">

**Comment by vdelendik** [comment]
it is planned to remove starter index.html age at all so keeping in TBD to verify that new approach hasn't such defect. Zafira (zebrunner insights) will be default page

**Comment by vdelendik** [comment]
it should be fixed in scope of https://github.com/qaprosoft/qps-infra/issues/227
