### ISSUE TITLE
Add possibility to select ANY devices for test execution based on specific mask.

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/qps-infra#5]
Most important to select ANY with Android version >= 5.1.1 or >=6.0
To configure it on suite level and probably in jenkins.

**Comment by vdelendik** [comment]
In 4.8 pipeline and infra we plan to provide fully independent approach to provide capabilities without any extra knowledge about infra/pipelines etc

**Comment by vdelendik** [comment]
@maksimsarychau each job will have "capabilities" text field which can be used to declare any W3C caps.
Also there is a way to override it's default value from testng suite xml file

**Comment by okamara** [comment]
@vdelendik or @maksimsarychau could you please provide details for verification this ticket?
