### ISSUE TITLE
Error creating database tables

### ISSUE THREAD

**Issue by nileshQK** [qaprosoft/qps-infra#62]
Hi,

I get these errors in the posgres database logs while deploying

C:\Users\niles>docker logs 42206c7562fd
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....LOG:  could not bind IPv6 socket: Cannot assign requested address
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  database system was shut down at 2019-05-13 05:20:37 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  pg_cron scheduler started
 done
server started
ALTER ROLE

CREATE EXTENSION

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  pg_cron scheduler shutting down
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down....LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2019-05-13 05:20:43 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  pg_cron scheduler started
LOG:  autovacuum launcher started
LOG:  database system was interrupted; last known up at 2019-05-13 05:20:44 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/1525370
LOG:  invalid record length at 0/15270D8: wanted 24, got 0
LOG:  redo done at 0/1525370
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  pg_cron scheduler started
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.NAME = $1
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.NAME = $1
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "monitors" does not exist at character 669
STATEMENT:  SELECT
                                        M.ID AS MONITOR_ID,
                                        M.NAME AS MONITOR_NAME,
                                        M.URL AS MONITOR_URL,
                                        M.HTTP_METHOD AS MONITOR_HTTP_METHOD,
                                        M.REQUEST_BODY AS MONITOR_REQUEST_BODY,
                                        M.ENV AS MONITOR_ENVIRONMENT,
                                        M.COMMENT AS MONITOR_COMMENT,
                                        M.TAG AS MONITOR_TAG,
                                        M.NOTIFICATIONS_ENABLED AS MONITOR_NOTIFICATIONS_ENABLED,
                                        M.MONITOR_ENABLED AS MONITOR_MONITOR_ENABLED,
                                        M.CRON_EXPRESSION AS MONITOR_CRON_EXPRESSION,
                                        M.RECIPIENTS AS MONITOR_RECIPIENTS,
                                        M.EXPECTED_CODE AS MONITOR_EXPECTED_CODE,
                                        M.SUCCESS AS MONITOR_SUCCESS,
                                        M.TYPE AS MONITOR_TYPE,
                                        M.CREATED_AT AS MONITOR_CREATED_AT,
                                        M.MODIFIED_AT AS MONITOR_MODIFIED_AT
                                FROM
                                        MONITORS M
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.NAME = $1
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

                                WHERE S.TOOL = $1
                                ORDER BY S.NAME ASC
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:
ERROR:  relation "settings" does not exist at character 319
STATEMENT:  SELECT
                                        S.ID AS SETTING_ID,
                                        S.NAME AS SETTING_NAME,
                                        S.VALUE AS SETTING_VALUE,
                        S.IS_ENCRYPTED AS SETTING_IS_ENCRYPTED,
                        S.TOOL AS SETTING_TOOL,
                        S.FILE AS SETTING_FILE,
                                        S.MODIFIED_AT AS SETTING_MODIFIED_AT,
                                        S.CREATED_AT AS SETTING_CREATED_AT
                                FROM
                                        SETTINGS S

**Comment by vdelendik** [comment]
@nileshQK glad to hear you could start postgres container on Windows. let's schedule session this week to take a look into the queries problems.

**Comment by vdelendik** [comment]
obsolete
