### ISSUE TITLE
Zafira login error 

### ISSUE THREAD

**Issue by HaykHarutyunyan** [qaprosoft/qps-infra#64]
Hi all. I want to login to Zafira by default login and password (login = admin,password=changeit) but it shows me the message "Invalid credentials"

**Comment by vdelendik** [comment]
@HaykHarutyunyan, please collect zafira docker logs and attach to the ticket.
Also log for postgres container could be useful as well as operation system type you use.

**Comment by vdelendik** [comment]
closing as of no reply
