### ISSUE TITLE
Upgrade sonarqube version to 7.7

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#65]
At the moment the qaprosoft docker image of sonarqube installs SonarQube ver.5.6.7.Is it possible to provide a qaprosoft image which builds SonarQube community ver.7.7 (that's the lataest one at the moment).
--

for details visit: https://github.com/qaprosoft/carina/issues/746

**Comment by vdelendik** [comment]
after the 4.8 qps-infra we unblocked sonar migration step

**Comment by vdelendik** [comment]
@sandinosanchez, please try to deploy on your laptop one of the latest sonarqube https://hub.docker.com/_/sonarqube/ using docker-compose

Requirements:
1) it should be started using embedded H2 database
2) volumes to persist data should be shared
3) investigate possibility to override default admin user
4) investigate possibility to add extra plugins (java, js, python as of now)
5) be able to setup NGiNX webserver in additions to it inside your docker-compose.yml corrcetly

feel free to ping me directly or in common channel in case of any blocker/question etc

**Comment by sandinosanchez** [comment]
Test scenario:

 1. Open http://demo.qaprosoft.com/sonarqube
 3. Check for version of sonarqube in footer
 4. On top menu navigate to rules
 5. On the left menu bar tap Languages 

Expected results:

 3. Version displayed = 8.2(build 32929)
 5. Languages displayed:
    - Java           - C#      - TypeScript
    - Python       - PHP    -  Ruby 
    - JavaScrip   - Scala  - Go

**Comment by sandinosanchez** [comment]
Test scenario:

1. Open http://demo.qaprosoft.com/sonarqube
2. Check for version of sonarqube in footer
3. On top menu navigate to rules
4. On the left menu bar tap Languages

Expected results:

  2. Version displayed = 7.1 (build 11001)
  4. Languages displayed:
    - Java - C# - TypeScript
    - Python - PHP - XML
    - JavaScrip - Flex

**Comment by dhreben** [comment]
Verified
