### ISSUE TITLE
update all qps-infra packages using en_US.UTF-8 locale

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#68]
龙 猫, [21.07.19 11:54]
[In reply to Vad Del]
Dear Val Del,
nothing worked after i followed. however, i got the answer said that docker container encoding using POSIX. when i get into jenkins_slave container, using locale, encoding which was using showed POSIX, and POSIX doesn't supply Chinese, it should be replace with en_US.UTF-8. And in order to change it permanently, docker images should be made by Dockerfile, now I have fixed my problem by setting the encoding in my Dockerfile, and then used the new jenkins-slave images to replace the old.

龙 猫, [21.07.19 11:54]
[In reply to Vad Del]
So, there were still some questions, can you supply all the images's Dockerfile inqps-infra, some docker images encoding is still POSIX, which could be unfriendly to some language using. I need the Dockerfile to rebuild new images.And what Dockerfiles i found in docker hub were not complete.For example, nginx Dockerfile , redis Dockerfile, elasticsearch Dockerfile.

**Comment by tbdyzm** [comment]
I‘m sorry to tell you that Jenkins-slave is still using POSIX.
![1](https://user-images.githubusercontent.com/41499236/61695916-ed3d5580-ad66-11e9-837b-01da1b6f04f1.png)

**Comment by vdelendik** [comment]
refactored all our own qaprosoft images to use en_US.UTF-8

**Comment by vdelendik** [comment]
it seems like all images are UTF-8
