### ISSUE TITLE
Update selenoid/vnc to latest versions

### ISSUE THREAD

**Issue by leonpros** [qaprosoft/qps-infra#74]
Currently using:
```
pull required docker images
docker pull selenoid/vnc:chrome_73.0
docker pull selenoid/vnc:firefox_66.0
```

Latest versions at the moment:
chrome_77.0
firefox_69.0

**Comment by vdelendik** [comment]
4.8+

https://github.com/qaprosoft/qps-infra/commit/5a27f5db3c3fb6c77dc6bf431fa6f11ebf58f4d5
