### ISSUE TITLE
registerZafiraCredentials job is gone

### ISSUE THREAD

**Issue by ivan-dobrinov** [qaprosoft/qps-infra#75]
Hi QAProsoft,

I see that the following job is no longer part of Management Jobs in Jenkins(latest version of QPS): 
registerZafiraCredentials
![image](https://user-images.githubusercontent.com/50947818/66201844-303b7380-e69c-11e9-963b-3bde34015117.png)

Can you please return it back or if not - can you please confirm a workaround?

Thanks in advance!

Cheers,
Ivan

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/commit/3fc708ccd93c5ad3e234b0ff00f06a0bb07b69ca

**Comment by ilya-varchenya** [comment]
It will be returned in 4.7+ release

**Comment by vdelendik** [comment]
@okamara, after starting 4.8-beta1 inside management_Jobs folder wre should have RegisterZafiraCredentials again

**Comment by okamara** [comment]
Verified

**Comment by okamara** [comment]
<img width="677" alt="Screen Shot 2019-12-20 at 7 15 38 PM" src="https://user-images.githubusercontent.com/32964663/71268097-29e49b80-235d-11ea-8e1f-f3869b0acc39.png">
