### ISSUE TITLE
Integrate 4.8 pipeline

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#76]
A lot of changes are planned in 4.8 pipeline and 4.2 zafira for launchers and capabilities transfer.

New approach should thoroughly tested.

**Comment by vdelendik** [comment]
4.8.2 is the right version for default pipeline. 
delivered changes can be tracked via:
https://github.com/qaprosoft/qps-pipeline/milestone/27?closed=1
https://github.com/qaprosoft/qps-pipeline/milestone/30?closed=1
https://github.com/qaprosoft/qps-pipeline/milestone/29

**Comment by vdelendik** [comment]
@okamara right after installing from scratch 4.8-beta1 version you should check in Manage Jenkins -> Configure System that QPS_PIPELINE_BRANCH=4.8

Also in scope of testing we should register new organization, repositorye and execute api/web jobs successfully

**Comment by okamara** [comment]
Configure System contains old version for me QPS_PIPELINE_BRANCH=4.87

**Comment by okamara** [comment]
Reverified now QPS_PIPELINE_BRANCH=4.8

**Comment by okamara** [comment]
jobs successfully were running
