### ISSUE TITLE
default zafira integrations are lost right after installing qps-infra from scratch

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/qps-infra#83]
With 4.1.79+ zafira default integrations for jenkins, rabbitmq etc are lost.
Required integrations should be enabled by default again (maybe init postgres script should be updated after refactoring Zafira integrations)

**Comment by vdelendik** [comment]
@okamara after installing from scratch qps-infra from 4.8-beta1 branch default integrations with CI/Automation server (jenkins) and Message Broker (rabbitmq) should be enabled and grren

**Comment by okamara** [comment]
Fixed.
