### ISSUE TITLE
setup automatic browsers update process on infra restart

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#85]
We can renimate the idea to use cm (configuration manager) to download fresh browsers images and generate quota automatically for that

**Comment by vdelendik** [comment]
in is configured to download latest 2 browsers versions for chrome, firefox and opera during **./setup.sh ip**

Also end-user could do it on his own running:
https://github.com/qaprosoft/qps-infra/blob/develop/selenoid/update.sh

Let's verify you can run it and download latest browsers. Note: preliminary remove let's say vnc_chrome 80 before running upgrade.sh

Also please submit one more documentation ticket to publish steps about upgrading browsers

**Comment by okamara** [comment]
Tested on local env.
