### ISSUE TITLE
setup.sh should support private and public ports

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#86]

**Comment by vdelendik** [comment]
@okamara, please test using branch: "86".
sudo ./clear.sh required as globally approach was reorganized. Moreover I recommend to remove completely qps-infra and clone again.
As a fix we moved selenoid into the same docker network and setup iintegration via container names, i.e. no more 4445 needed.
PR: #113

**Comment by okamara** [comment]
Verified on 86 branch. Fixed.
