### ISSUE TITLE
hide debug JAVA_OPTS for zafira container

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#87]
as we don't support classic way to transfer JAVA_OPTS into the zafira we can remove commented lines with example to enable debug

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-infra/commit/403d7421b4fe7826a06de131c2f5fec5dcefcdac

@okamara, verify that there is no JAVA_OPTS even commented in docker-compose.yml after execution ./setup.sh script

**Comment by okamara** [comment]
I see only  - ES_JAVA_OPTS=-Xms2g -Xmx2g. @vdelendik is it correct?

**Comment by okamara** [comment]
Fixed.
