### ISSUE TITLE
Organize quota automatically based on cm and latest selenoid browsers images

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#88]

**Comment by vdelendik** [comment]
Feature is available in 5.0-beta8 branch of qps-infra.
1) no more ggr and default hardcoded quota.xml
2) during "./setup.sh <ip>" we start selenoid ConfigurationManager to download latest 2 versions of chrome/firefox and opera browsers. It also generate fresh browsers.json

So test scenario is:
1) run sudo ./clear.sh and completely remove qps-infra
2) remove aerokube folder if any
sudo rm -rf ~/.aerokube
3) clone qps-infra and switch to 5.0-beta8 branch
4) ./setup.sh <ip>
-> During setup latest browser images should be downloaded
![image](https://user-images.githubusercontent.com/4551455/80872301-b4e58300-8cb9-11ea-80f3-48cf1f8651ff.png)

-> run "docker images" to verify that everything is downloaded as needed
![image](https://user-images.githubusercontent.com/4551455/80872334-e65e4e80-8cb9-11ea-84f7-2985f074b0f7.png)

-> verify that qps-infra/selenoid/browsers.json is generated with chrme 81 and 80, firefox 75 and 74, opera 67 and 66

**Comment by okamara** [comment]
Tested. Fixed.
