### ISSUE TITLE
declare default selenium integration  using zafira_init.sh

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#89]
Adjust zafira init shell script to be able to register any integration with:
selenium
mcloud
aerokube
browserstack
saucelabs

need to think howto provide urls and creds correctly.
changes should be ported into the zafira github repo as well

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/qps-infra/commit/dc0cfa8ede6dd8396ecf22e099e2a2cb21dedac3

**Comment by vdelendik** [comment]
@okamara to test this feature you have to:
1. sudo ./clear.sh
2. switch to 4.8-beta1 branch (qps-infra repo)
3. ./setup.sh <ip>
4. make sure to declare any values for variables.env like below:
# SELENIUM - https://github.com/qaprosoft/carina-grid
SELENIUM_ENABLED=true
SELENIUM_URL=http://demo.qaprosoft.com/ggr/wd/hub
SELENIUM_USER=demo
SELENIUM_PASSWORD=demo

# MCLOUD - https://github.com/qaprosoft/mcloud
MCLOUD_ENABLED=true
MCLOUD_URL=https://hub.zebrunner.com/wd/hub
MCLOUD_USER=u
MCLOUD_PASSWORD=p

# ZEBRUNNER - https://zebrunner.com/
ZEBRUNNER_ENABLED=true
ZEBRUNNER_URL=https://hub.zebrunner.com/wd/hub
ZEBRUNNER_USER=u
ZEBRUNNER_PASSWORD=p

# AEROKUBE - http://browsers.aerokube.com
AEROKUBE_ENABLED=true
AEROKUBE_URL=https://browsers.aerokube.com:4444/wd/hub
AEROKUBE_USER=u
AEROKUBE_PASSWORD=p

# BROWSERSTACK - https://www.browserstack.com
BROWSERSTACK_ENABLED=true
BROWSERSTACK_URL=https://hub-cloud.browserstack.com/wd/hub
BROWSERSTACK_USER=u
BROWSERSTACK_PASSWORD=p


After login into the zafira all integrations for test environment providers should be enabled (red status is ok for now)

**Comment by okamara** [comment]
Verified. Fixed.
