### ISSUE TITLE
docker not found

### ISSUE THREAD

**Issue by essamsalah** [qaprosoft/qps-infra#92]
Hi,

Trying to make a simple pipeline that creates a docker container following this approach [Using Docker with Pipeline](https://jenkins.io/doc/book/pipeline/docker/)

The build will fail with the following error:
`dokcer: not found`
`ERROR: script returned exit code 127`

**Comment by vdelendik** [comment]
@essamsalah, please explain in details where and what did you do...
according to the error you are trying to execute "docker" command where docker is not installed

**Comment by essamsalah** [comment]
My pipeline looks like this in Jenkins:

```
pipeline {
    agent {
        docker { image 'node:7-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
```
While Jenkins itself runs in docker, the pipeline is not able to run docker-cli although it is already installed on the host.

**Comment by essamsalah** [comment]
Hi,

The missing piece here is to have docker-cli installed on the jenkins-image and mount the docker-socket from the host machine.

This will allow the pipeline to use docker from the host which enable creating news images or run containers from the Jenkins pipeline.

The changes I propose on your repo:
1. Add the `/var/run/docker.sock:/var/run/docker.sock` to the docker-compose.yml file
2. Add the last Run command from [here](https://github.com/getintodevops/jenkins-withdocker/blob/master/Dockerfile) to the Dockerfile whcih creates your Jenkins image

**Comment by ilya-varchenya** [comment]
@okamara, please test it with next scenario:
1. Make changes on your test machine in qps-infra (branch: [dnf](https://github.com/qaprosoft/qps-infra/tree/dnf)) and make local jenkins-slave container (branch: [dnf](https://github.com/qaprosoft/jenkins-slave/tree/dnf))
2. Get id of your jenkin-slave container with **docker ps**
3. Go inside of your container: **docker exec -it <container_id> bash**
4. Try to run **docker ps** command - it must show the same information as it wan on first step

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/qps-infra/pull/110
https://github.com/qaprosoft/jenkins-slave/pull/6

**Comment by vdelendik** [comment]
closing:
https://github.com/qaprosoft/jenkins-slave/releases/tag/latest

stop infra, remove jenkins-slave latest image, start infra again

**Comment by okamara** [comment]
@ilya-varchenya could you please explain what exactly information I should compare and see in 4 step(Try to run docker ps command - it must show the same information as it wan on first step) ?
