### ISSUE TITLE
JOB_URL_VISIBILITY jenkins integration property is missed

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#94]
we should have by default "JOB_URL_VISIBILITY=true" property for default ci/jenkins integration
![image](https://user-images.githubusercontent.com/4551455/71384008-f1a8bb80-25ef-11ea-8910-cc98191c26c0.png)

it seems like isssue with zafira-init.sh which is used to setup default integration or bug in zafira reporting tool itself

**Comment by ilya-varchenya** [comment]
@okamara, please test using develop branch for qps-infra.
sudo ./clear.sh is a must.
Here must be true
![image](https://user-images.githubusercontent.com/44428408/71414995-abdd0900-266a-11ea-8143-4366b639b5f0.png)

**Comment by okamara** [comment]
Fixed.
